name: doc_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.4+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  easy_localization: ^3.0.3
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.5
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  intl: ^0.19.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0

dev_dependencies:
  #A build system for Dart code generation and modular compilation
  build_runner: ^2.4.7

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  # Code generator (mainly used with cubit & retrofit)
  freezed: ^2.4.5
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/
    - .env.development
    - .env.production
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
