default_platform(:android)


default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor Production --target lib/main_prod.dart --no-tree-shake-icons"
    firebase_app_distribution(
        # in Project settings firebase 
        app: "1:149120264085:android:a8e1fe1a231020bb89389c",
        # in cmd command firebase login:ci
        firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
        # constants
        android_artifact_type: "APK",
        # in build => app => outputs => flutter-apk => app-production-release.apk 
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        # tester email 
        testers: "fady46t45f@gmail.com",
        # constants
        release_notes: "Testing something with GitHub Actions, trying to push directly from master branch",
  )
  end
end
